# Generated by Django 6.1.1 on 2026-10-06 15:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EntrepriseApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expedition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('ville_depart', models.CharField(max_length=100)),
                ('ville_arrivee', models.CharField(max_length=100)),
                ('poids_kg', models.DecimalField(validators=[django.core.validators.MinValueValidator(0)])),
                ('date_souhaitee', models.DateField()),
                ('description', models.TextField()),
                ('statut', models.CharField(choices=[('b', 'publiee'), ('a', 'attribuee'), ('e', 'En cours'), ('l', 'livree'), ('an', 'annuler')], default='publies', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expeditions', to='EntrepriseApp.entreprise')),
            ],
        ),
    ]
