# Generated by Django 6.1.1 on 2026-10-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatricule', models.CharField(max_length=20, unique=True)),
                ('type_vehiciule', models.CharField(choices=[('camion', 'Camion'), ('voiture', 'Voiture'), ('moto', 'Moto')], max_length=50)),
                ('capacite_kg', models.IntegerField()),
                ('disponible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
